server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Project Task service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/project_flow_db?charSet=UTF8}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    baseline-version: 1
    baseline-description: "init"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

tech_dep:
  app:
    jwtExpirationMs: 3600000 # 1 hour
    jwtRefreshExpirationMs: 3600000 # 1 hour
    verificationExpirationMs: 21600000 # 6 hours
    clientUrl: http://localhost:5173